spring:
   datasource:
      sakura:
         username: duke
         password: shimon
         jdbc-url: jdbc:mysql://localhost:3306/kingdom?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
         driver-class-name: com.mysql.cj.jdbc.Driver