server:
  port: 8086
  
logging:
  level:
    org:
      springframework:
        cloud: DEBUG

spring:
  profiles:
    active: native
  application:
    name: sakura-config-central
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config