server:
  port: 8090
  
spring:
  application:
    name: sakura-kingdom
  cloud:
    config:
      uri: http://localhost:8086
  datasource:
    sakura:
      username: duke
      password: shimon
      jdbc-url: jdbc:mysql://localhost:3306/kingdom?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  environment: dev
  server:
      # 关闭自我保护
      enable-self-preservation: false
      # 清理服务器
      eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      # enable heartbeat check with eureka server
      enabled: false
    service-url:
      defaultZone: http://localhost:8091/eureka/
    register-with-eureka: false
    fetch-registry: false
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
